### ISSUE TITLE
Documentation for rdf_page_to_resource

### ISSUE THREAD

**Issue by white-gecko** [AKSW/jekyll-rdf#217]
There is no documentation for `rdf_page_to_resource` filter (https://github.com/white-gecko/jekyll-rdf/blob/develop/lib/jekyll/filters/rdf_page_to_resource.rb) in the README.

**Comment by Simaris** [comment]
the reason is, that it is not a filter.
it is actually a helper module that most other filters do not use

**Comment by white-gecko** [comment]
Please rename `rdf_message` to `rdf_debug_message` and move the helper filters to helpers.
