### ISSUE TITLE
Include more files

### ISSUE THREAD

**Issue by MichalMed** [AKSW/jekyll-rdf#286]
I have my data stored in multiple files. I'd like to use more of them in path, eventually read the data from the web.

**Comment by white-gecko** [comment]
In this case the best would be to use a SPARQL endpoint that has all of the data loaded. For the configuration please see https://github.com/AKSW/jekyll-rdf#plugin-configuration-_configyml the `remote > endpoint` part.
Reading the data from the web would also require some intermediate extra service.
